### ISSUE TITLE
Python 3 Issue

### ISSUE THREAD

**Issue by maangulo12** [morgan-del/flask-triangle#28]
First of all, I just want to say how awesome it is for providing this extension for Flask. 

I would like to integrate this extension into my Flask application, but I am getting this message error:

Traceback (most recent call last):
  File "C:/workspace/pycharm/aaa/application.py", line 12, in <module>
    from app.core import app
  File "C:\workspace\pycharm\aaa\app\core.py", line 14, in <module>
    from flask.ext.triangle import Triangle
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\flask\exthook.py", line 62, in load_module
    __import__(realname)
  File "C:\Python34\lib\site-packages\flask_triangle\__init__.py", line 17, in <module>
    from .triangle import Triangle
  File "C:\Python34\lib\site-packages\flask_triangle\triangle.py", line 17, in <module>
    from .jinja import angular_filter, widget_test, TriangleUndefined
  File "C:\Python34\lib\site-packages\flask_triangle\jinja.py", line 18, in <module>
    from .widget import Widget
  File "C:\Python34\lib\site-packages\flask_triangle\widget.py", line 18, in <module>
    from flask_triangle.helpers import UnicodeMixin, HTMLString
  File "C:\Python34\lib\site-packages\flask_triangle\helpers\__init__.py", line 12, in <module>
    from .html import HTMLString
  File "C:\Python34\lib\site-packages\flask_triangle\helpers\html.py", line 14, in <module>
    class HTMLString(unicode):
NameError: name 'unicode' is not defined

I have read the documentation several times and have tried different ways to solve this problem. If I am missing any python packages (besides Flask-Triangle) that needs to be installed on my system, please let me know.

Thanks.

**Comment by UweWindt** [comment]
I just found  the same issue with python 3.4

**Comment by cameron-white-janrain** [comment]
I have the same problem with Python 3.5.1 on OS X Yosemite 10.10.5

**Comment by cameron-white-janrain** [comment]
@UweWindt It looks like just the version in pip is broken (https://pypi.python.org/pypi/Flask-Triangle/0.5.4 )which is says is version 0.5.4. However the version 0.5.3 (https://github.com/morgan-del/flask-triangle/tree/be6ba54f3d9e22a3d8fddb9d7aa08d339ad9214f) does not have this issue.

**Comment by emartinelli** [comment]
This was fixed on master [branch](https://github.com/morgan-del/flask-triangle/blob/master/flask_triangle/helpers/html.py). However, package 0.5.4 seems to be a python 3.x non-compatible version of this same file on pip. See also: #14

**Comment by Calabashmc** [comment]
Same problem for me.  Python 3.4.
